server {
    listen 127.0.0.1:8080;
    server_name freeapi.kenoma.me;

    root /opt/FreeApi/web-dist;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        auth_basic off;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
